"""
HuggingFace MedGemma Pipeline for Task 2.

Uses google/medgemma-4b-it locally via the HuggingFace transformers library
(AutoModelForImageTextToText + AutoProcessor) to generate structured
medical reports from PneumoniaMNIST chest X-ray images.

Usage:
    python -m task2_report_generation.run_task2_hf
    python -m task2_report_generation.run_task2_hf --num_samples 10 --temperature 0.3
"""

import json
import logging
import os
import re
import time
from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np
import torch
from PIL import Image

from task2_report_generation.prompts import PromptPair, PromptStrategy, get_all_strategies, get_prompt
from task2_report_generation.sample_selection import SelectedSample

logger = logging.getLogger(__name__)

CLASS_NAMES = {0: "Normal", 1: "Pneumonia"}

# ---------------------------------------------------------------------------
# MedGemma report dataclass (mirrors VLMReport for compatibility)
# ---------------------------------------------------------------------------

@dataclass
class MedGemmaReport:
    """Report generated by HuggingFace MedGemma."""
    image_index: int
    model_name: str
    provider: str          # always "huggingface"
    strategy: PromptStrategy
    system_prompt: str
    user_prompt: str
    raw_response: str
    ground_truth: int
    cnn_prediction: int
    cnn_confidence: float
    generation_time_s: float

    def to_dict(self) -> Dict:
        return {
            "image_index": self.image_index,
            "model_name": self.model_name,
            "provider": self.provider,
            "strategy": self.strategy.value,
            "system_prompt": self.system_prompt,
            "user_prompt": self.user_prompt,
            "raw_response": self.raw_response,
            "ground_truth": self.ground_truth,
            "cnn_prediction": self.cnn_prediction,
            "cnn_confidence": self.cnn_confidence,
            "generation_time_s": round(self.generation_time_s, 2),
        }


# ---------------------------------------------------------------------------
# Image preparation
# ---------------------------------------------------------------------------

def prepare_image(image_array: np.ndarray, target_size: int = 224) -> Image.Image:
    """Convert a PneumoniaMNIST numpy image to a PIL RGB image.

    MedGemma4b expects RGB images (3-channel). PneumoniaMNIST images are
    grayscale — we convert to RGB by replicating across channels.

    Args:
        image_array: Numpy array, shape (H, W) or (H, W, 1), uint8 or float.
        target_size: Target square size for upscaling (default: 224 or 512).

    Returns:
        PIL Image in RGB mode, sized (target_size × target_size).
    """
    # Normalize to uint8
    if image_array.dtype != np.uint8:
        arr = (image_array * 255).clip(0, 255).astype(np.uint8)
    else:
        arr = image_array

    # Remove singleton channel dimension
    if arr.ndim == 3 and arr.shape[2] == 1:
        arr = arr.squeeze(axis=2)

    # Convert grayscale → RGB
    pil_gray = Image.fromarray(arr, mode="L")
    pil_upscaled = pil_gray.resize((target_size, target_size), Image.LANCZOS)
    pil_rgb = pil_upscaled.convert("RGB")

    return pil_rgb


# ---------------------------------------------------------------------------
# HF MedGemma pipeline
# ---------------------------------------------------------------------------

class HFMedGemmaPipeline:
    """Pipeline for generating medical reports using HuggingFace MedGemma.

    Loads google/medgemma-4b-it (or a compatible model) locally and
    generates structured radiology reports for chest X-ray images.

    The model uses the chat template format required by MedGemma:
        [{"role": "user", "content": [
            {"type": "image"},
            {"type": "text", "text": "..."},
        ]}]
    """

    def __init__(
        self,
        model_id: str = "google/medgemma-4b-it",
        temperature: float = 0.3,
        max_new_tokens: int = 1024,
        image_size: int = 512,
        device_map: str = "auto",
        torch_dtype: Optional[torch.dtype] = None,
    ) -> None:
        """Initialise the HuggingFace MedGemma pipeline.

        Args:
            model_id: HuggingFace model repo ID.
            temperature: Sampling temperature (lower = more deterministic).
            max_new_tokens: Maximum number of tokens to generate.
            image_size: Image resize target before feeding to the model.
            device_map: Device map for model loading ('auto', 'cpu', 'cuda').
            torch_dtype: Torch dtype; defaults to bfloat16 on GPU, float32 on CPU.
        """
        self.model_id = model_id
        self.temperature = temperature
        self.max_new_tokens = max_new_tokens
        self.image_size = image_size

        device = "cuda" if torch.cuda.is_available() else "cpu"
        logger.info(
            "[HFMedGemmaPipeline] Device: %s | Model: %s",
            device.upper(), model_id,
        )

        # Resolve dtype
        if torch_dtype is None:
            torch_dtype = torch.bfloat16 if device == "cuda" else torch.float32

        logger.info("[HFMedGemmaPipeline] Loading model (this may take a few minutes)...")
        self._load_model(model_id, device_map, torch_dtype)
        logger.info("[HFMedGemmaPipeline] Model ready.")

    def _load_model(
        self,
        model_id: str,
        device_map: str,
        torch_dtype: torch.dtype,
    ) -> None:
        """Load the model and processor from HuggingFace Hub."""
        from transformers import AutoModelForImageTextToText, AutoProcessor

        self.processor = AutoProcessor.from_pretrained(model_id)
        self.model = AutoModelForImageTextToText.from_pretrained(
            model_id,
            torch_dtype=torch_dtype,
            device_map=device_map,
        )
        self.model.eval()

    def _build_messages(
        self,
        prompt_pair: PromptPair,
        has_image: bool = True,
    ) -> List[Dict]:
        """Build the chat message list for MedGemma.

        MedGemma uses a specific multimodal chat template where the image
        placeholder must appear before the text in the user content list.

        Args:
            prompt_pair: System + user prompt.
            has_image: Whether to include the image placeholder.

        Returns:
            Messages list suitable for processor.apply_chat_template().
        """
        user_content = []
        if has_image:
            user_content.append({"type": "image"})
        user_content.append({"type": "text", "text": prompt_pair.user_prompt})

        messages = []
        # MedGemma supports system via first user message or system role
        if prompt_pair.system_prompt:
            messages.append({
                "role": "system",
                "content": [{"type": "text", "text": prompt_pair.system_prompt}],
            })
        messages.append({
            "role": "user",
            "content": user_content,
        })
        return messages

    @torch.inference_mode()
    def generate_report(
        self,
        image: Image.Image,
        strategy: PromptStrategy,
        image_index: int,
        ground_truth: int = 0,
        cnn_prediction: int = 0,
        cnn_confidence: float = 0.5,
    ) -> MedGemmaReport:
        """Generate a medical report for a single image.

        Args:
            image: PIL Image (RGB, already upscaled).
            strategy: Prompt strategy to use.
            image_index: Image identifier for logging.
            ground_truth: Ground truth label (0/1).
            cnn_prediction: CNN predicted label (0/1).
            cnn_confidence: CNN confidence score [0, 1].

        Returns:
            MedGemmaReport with generated text.
        """
        prompt_pair = get_prompt(
            strategy=strategy,
            cnn_prediction=cnn_prediction,
            ground_truth=ground_truth,
            cnn_confidence=cnn_confidence,
        )

        logger.info(
            "Generating: image=%d, strategy=%s, GT=%s, CNN=%s (%.2f)",
            image_index, strategy.value,
            CLASS_NAMES[ground_truth], CLASS_NAMES[cnn_prediction], cnn_confidence,
        )

        messages = self._build_messages(prompt_pair, has_image=True)

        # Tokenise with chat template
        text_input = self.processor.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        inputs = self.processor(
            text=text_input,
            images=[image],
            return_tensors="pt",
        ).to(self.model.device)

        t_start = time.time()
        output_ids = self.model.generate(
            **inputs,
            max_new_tokens=self.max_new_tokens,
            do_sample=self.temperature > 0,
            temperature=self.temperature if self.temperature > 0 else None,
            pad_token_id=self.processor.tokenizer.eos_token_id,
        )
        elapsed = time.time() - t_start

        # Decode only the newly generated tokens
        n_input_tokens = inputs["input_ids"].shape[1]
        new_tokens = output_ids[0, n_input_tokens:]
        raw_response = self.processor.decode(new_tokens, skip_special_tokens=True).strip()

        logger.info(
            "Generated %d tokens in %.1fs for image %d (strategy=%s)",
            len(new_tokens), elapsed, image_index, strategy.value,
        )

        return MedGemmaReport(
            image_index=image_index,
            model_name=self.model_id,
            provider="huggingface",
            strategy=strategy,
            system_prompt=prompt_pair.system_prompt,
            user_prompt=prompt_pair.user_prompt,
            raw_response=raw_response,
            ground_truth=ground_truth,
            cnn_prediction=cnn_prediction,
            cnn_confidence=cnn_confidence,
            generation_time_s=elapsed,
        )

    def generate_all(
        self,
        samples: List[SelectedSample],
        strategies: Optional[List[PromptStrategy]] = None,
        output_dir: str = "./reports/generated_reports",
        image_size: Optional[int] = None,
    ) -> List[MedGemmaReport]:
        """Generate reports for all samples and all strategies.

        Args:
            samples: Selected image samples.
            strategies: Prompt strategies (default: all three).
            output_dir: Directory to save individual JSON reports.
            image_size: Override image size for upscaling.

        Returns:
            Flat list of all MedGemmaReport objects.
        """
        if strategies is None:
            strategies = get_all_strategies()

        size = image_size or self.image_size
        os.makedirs(output_dir, exist_ok=True)
        model_safe = self.model_id.replace("/", "_").replace(":", "-")
        all_reports = []

        for i, sample in enumerate(samples):
            logger.info(
                "Sample %d/%d — index=%d | GT=%s | CNN=%s",
                i + 1, len(samples), sample.index,
                CLASS_NAMES[sample.ground_truth],
                CLASS_NAMES[sample.cnn_prediction],
            )

            # Prepare image: numpy array → upscaled RGB PIL
            pil_image = prepare_image(sample.image, target_size=size)

            for strategy in strategies:
                report = self.generate_report(
                    image=pil_image,
                    strategy=strategy,
                    image_index=sample.index,
                    ground_truth=sample.ground_truth,
                    cnn_prediction=sample.cnn_prediction,
                    cnn_confidence=sample.cnn_confidence,
                )
                all_reports.append(report)

                # Save individual report
                fname = f"sample_{sample.index}_{model_safe}_{strategy.value}.json"
                fpath = os.path.join(output_dir, fname)
                with open(fpath, "w") as f:
                    json.dump(report.to_dict(), f, indent=2)
                logger.info("Saved: %s", fpath)

        # Save aggregated
        agg_path = os.path.join(output_dir, f"all_reports_hf_{model_safe}.json")
        with open(agg_path, "w") as f:
            json.dump([r.to_dict() for r in all_reports], f, indent=2)
        logger.info(
            "All reports saved → %s (%d total)", agg_path, len(all_reports)
        )

        return all_reports
